# Generated by Django 4.2.3 on 2023-07-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(default='Syria'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
